use crate::agent::Agent;
use crate::config::SimulationConfig;
use crate::engine::SimulationEvent;
use crate::world::World;
use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::PathBuf;
use uuid::Uuid;

/// Records the narrative history of the simulation
pub struct Chronicle {
    output_dir: PathBuf,
    writer: BufWriter<File>,
    event_count: usize,
}

impl Chronicle {
    pub fn new(output_dir: &str, name: &str) -> anyhow::Result<Self> {
        let output_path = PathBuf::from(output_dir);
        fs::create_dir_all(&output_path)?;

        let chronicle_path = output_path.join("chronicle.md");
        let file = File::create(&chronicle_path)?;
        let writer = BufWriter::new(file);

        Ok(Self {
            output_dir: output_path,
            writer,
            event_count: 0,
        })
    }

    /// Write the chronicle header
    pub fn write_header(
        &mut self,
        config: &SimulationConfig,
        world: &World,
        agents: &HashMap<Uuid, Agent>,
    ) -> anyhow::Result<()> {
        writeln!(self.writer, "# {}", config.name)?;
        writeln!(self.writer)?;
        writeln!(self.writer, "> A Terrarium Simulation Chronicle")?;
        writeln!(self.writer)?;
        writeln!(self.writer, "## Initial Conditions")?;
        writeln!(self.writer)?;
        writeln!(self.writer, "- **World Size**: {}x{}", config.world.width, config.world.height)?;
        writeln!(self.writer, "- **Population**: {} agents", agents.len())?;
        writeln!(self.writer, "- **Planned Epochs**: {}", config.simulation.epochs)?;
        if let Some(seed) = config.simulation.seed {
            writeln!(self.writer, "- **Random Seed**: {}", seed)?;
        }
        writeln!(self.writer)?;

        // List initial agents
        writeln!(self.writer, "### The Inhabitants")?;
        writeln!(self.writer)?;

        for agent in agents.values() {
            writeln!(
                self.writer,
                "- **{}**: {} at ({}, {})",
                agent.name,
                agent.mind.personality.describe(),
                agent.body.position.0,
                agent.body.position.1
            )?;
        }

        writeln!(self.writer)?;
        writeln!(self.writer, "---")?;
        writeln!(self.writer)?;
        writeln!(self.writer, "## Chronicle")?;
        writeln!(self.writer)?;

        self.writer.flush()?;
        Ok(())
    }

    /// Record a significant event
    pub fn record_event(&mut self, epoch: usize, event: &SimulationEvent) -> anyhow::Result<()> {
        self.event_count += 1;

        // Only record events that are actually significant
        if event.description.is_empty() {
            return Ok(());
        }

        writeln!(self.writer, "**Epoch {}**: {}", epoch, event.description)?;
        writeln!(self.writer)?;

        // Flush periodically
        if self.event_count % 10 == 0 {
            self.writer.flush()?;
        }

        Ok(())
    }

    /// Write the chronicle footer
    pub fn write_footer(
        &mut self,
        world: &World,
        agents: &HashMap<Uuid, Agent>,
    ) -> anyhow::Result<()> {
        writeln!(self.writer)?;
        writeln!(self.writer, "---")?;
        writeln!(self.writer)?;
        writeln!(self.writer, "## Final State")?;
        writeln!(self.writer)?;
        writeln!(self.writer, "- **Final Epoch**: {}", world.epoch)?;
        writeln!(self.writer, "- **Final Season**: {}", world.season_name())?;

        let alive = agents.values().filter(|a| a.is_alive()).count();
        let dead = agents.len() - alive;
        writeln!(self.writer, "- **Survivors**: {} ({} perished)", alive, dead)?;
        writeln!(self.writer)?;

        // Summary of survivors
        if alive > 0 {
            writeln!(self.writer, "### Survivors")?;
            writeln!(self.writer)?;

            for agent in agents.values().filter(|a| a.is_alive()) {
                writeln!(
                    self.writer,
                    "- **{}** (age {}): {:.0}% health, {} food, {} materials, {} tools",
                    agent.name,
                    agent.body.age,
                    agent.body.health * 100.0,
                    agent.body.inventory.food,
                    agent.body.inventory.materials,
                    agent.body.inventory.tools,
                )?;
            }
        }

        writeln!(self.writer)?;
        writeln!(self.writer, "---")?;
        writeln!(self.writer)?;
        writeln!(self.writer, "*Chronicle generated by Terrarium v{}*", env!("CARGO_PKG_VERSION"))?;

        self.writer.flush()?;
        Ok(())
    }
}
